### ISSUE TITLE
2.0 release tracking

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/surf#107]
This is a tracking list of work we need to do for a 2.0 release. It's not much, and most of the API will stay the same. But still, if we have multiple changes that come together it's best to batch them (: 

## Tasks
- [x] upgrade isahc to a 0.3.0 compatible version https://github.com/http-rs/surf/issues/100
- [x] move to [`http-client`](https://github.com/http-rs/http-client/issues/2) (ref https://github.com/http-rs/surf/pull/66)
- [x]  remove generic param and use dynamic dispatch instead https://github.com/http-rs/surf/issues/69
- [x]  replace `surf::Exception` with `surf::Error` that is a re-export of `anyhow::Error` https://github.com/http-rs/surf/issues/86
- [x] use `surf::Request` and `surf::Response` in middleware #131 
- [ ] Connection pooling for Client / HttpClient https://github.com/http-rs/surf/issues/224
- [ ] Possibly use the async-h1 HttpClient by default rather than Isahc https://github.com/http-rs/surf/issues/217
- ~~[ ] wasm compatibility #210~~

**Comment by Fishrock123** [comment]
Updated the list slightly, but I think this is better tracked in the milestone. See https://github.com/http-rs/surf/milestone/1
